# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uxFoAbQjKfsCHUnW3y38h74oQVwNLsJx
"""

import tensorflow as tf
print(tf.__version__)

!pip install tf_keras

import tf_keras as keras

model = keras.models.load_model("keras_model.h5", compile=False)

print("Model loaded successfully!")

import numpy as np
from PIL import Image
# Read class names
with open("labels.txt", "r") as f:
    class_names = [line.strip() for line in f.readlines()]
# Open the image
image = Image.open("Test.jpeg").convert("RGB")
# Resize to the model input size
image = image.resize((224, 224))
# Convert to numpy array
image_array = np.asarray(image, dtype=np.float32)
# Normalize (Teachable Machine requirement)
image_array = (image_array / 127.5) - 1
# Add batch dimension
image_array = np.expand_dims(image_array, axis=0)
# Predict
prediction = model.predict(image_array)

index = np.argmax(prediction)
confidence = prediction[0][index]

print("Prediction:", class_names[index])
print(f"Confidence: {confidence*100:.2f}%")